# Simplified Ollama Deployment
# No persistent storage - model downloads on first use
#
# Deployment: kubectl apply -f deployment-ollama.yaml
# Access: http://ollama.chainfetch.svc.cluster.local:11434
#
apiVersion: v1
kind: Namespace
metadata:
  name: chainfetch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: chainfetch
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        - name: OLLAMA_ORIGINS
          value: "*"
        readinessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/tags
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "6Gi"
            cpu: "1"
          limits:
            memory: "12Gi"
            cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: chainfetch
  labels:
    app: ollama
spec:
  type: ClusterIP
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama