apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chainfetch-ingress
  namespace: chainfetch
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chainfetch.app
        - www.chainfetch.app
        - api.chainfetch.app
      secretName: chainfetch-tls
  rules:
    - host: chainfetch.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chainfetch-web
                port:
                  number: 80
    - host: www.chainfetch.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chainfetch-web
                port:
                  number: 80
    - host: api.chainfetch.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chainfetch-web
                port:
                  number: 80