apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  addresses:
    - 95.216.11.35/32  # VPS public IP
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-ip
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-ip 