apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-longhorn
  namespace: chainfetch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
